name: CI for Churn Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupération du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Configurer Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Entraîner le modèle
    - name: Train the model
      run: |
        python train.py
      env:
        PYTHONHASHSEED: 0  # Assurez-vous de la reproductibilité si applicable

    # Étape 5 : Tester l'application Flask
    - name: Run Flask tests
      run: |
        python -m pytest test_app.py --disable-warnings

    # Facultatif : Vous pouvez aussi démarrer l'application pour des tests manuels.
    - name: Start Flask server
      run: |
        python app.py &
      env:
        FLASK_ENV: testing
